import PlaygroundSupport
import TortoiseGraphics
import CoreGraphics

let myFrame = CGRect(x: 0, y: 0, width: 500, height: 500)
let canvas = PlaygroundCanvas(frame: myFrame)
canvas.frameRate = 300
canvas.color = .white
PlaygroundPage.current.liveView = canvas

canvas.drawing { turtle in
    
    for _ in 1...85 {
        
        // Turn a random amount
        let turn = turtle.random(360)
        turtle.left(turn)
        
        // Draw a random line length
        let distance = turtle.random(200)
        turtle.forward(distance)
        
        // back to centre of canvas and original heading
        turtle.penUp()
        turtle.goto(0, 0)
        turtle.setHeading(0)
        turtle.penDown()
        
    }
    
    
    
    //draw clock
    turtle.penColor(.amber)
    turtle.penSize(2)
    turtle.penUp()
    turtle.goto(-50,180)
    turtle.penDown()
    turtle.curve(withSides: 15, withSize: 20, drawSides: 15)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(45)
    turtle.penDown()
    turtle.right(90)
    turtle.forward(50)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(50)
    turtle.penDown()
    turtle.left(100)
    turtle.forward(30)
    
    //draw clock
    turtle.penColor(.black)
    turtle.penSize(2)
    turtle.penUp()
    turtle.goto(150,250)
    turtle.penDown()
    turtle.curve(withSides: 15, withSize: 20, drawSides: 15)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(45)
    turtle.penDown()
    turtle.right(90)
    turtle.forward(50)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(50)
    turtle.penDown()
    turtle.left(100)
    turtle.forward(30)
    
    //draw clock
    turtle.penColor(.blue)
    turtle.penSize(2)
    turtle.penUp()
    turtle.goto(-180,200)
    turtle.penDown()
    turtle.curve(withSides: 15, withSize: 20, drawSides: 15)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(45)
    turtle.penDown()
    turtle.right(90)
    turtle.forward(50)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(50)
    turtle.penDown()
    turtle.left(100)
    turtle.forward(30)
    
    //draw clock
    turtle.penColor(.blueGrey)
    turtle.penSize(2)
    turtle.penUp()
    turtle.goto(20,50)
    turtle.penDown()
    turtle.curve(withSides: 15, withSize: 20, drawSides: 15)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(45)
    turtle.penDown()
    turtle.right(90)
    turtle.forward(50)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(50)
    turtle.penDown()
    turtle.left(100)
    turtle.forward(30)
    
    //draw clock
    turtle.penColor(.brown)
    turtle.penSize(2)
    turtle.penUp()
    turtle.goto(120,110)
    turtle.penDown()
    turtle.curve(withSides: 15, withSize: 20, drawSides: 15)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(45)
    turtle.penDown()
    turtle.right(90)
    turtle.forward(50)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(50)
    turtle.penDown()
    turtle.left(100)
    turtle.forward(30)
    
    //draw clock
    turtle.penColor(.cyan)
    turtle.penSize(2)
    turtle.penUp()
    turtle.goto(-100,30)
    turtle.penDown()
    turtle.curve(withSides: 15, withSize: 20, drawSides: 15)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(45)
    turtle.penDown()
    turtle.right(90)
    turtle.forward(50)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(50)
    turtle.penDown()
    turtle.left(100)
    turtle.forward(30)

    //draw clock
    turtle.penColor(.deepOrange)
    turtle.penSize(2)
    turtle.penUp()
    turtle.goto(-100,-150)
    turtle.penDown()
    turtle.curve(withSides: 15, withSize: 20, drawSides: 15)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(45)
    turtle.penDown()
    turtle.right(90)
    turtle.forward(50)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(50)
    turtle.penDown()
    turtle.left(100)
    turtle.forward(30)
    
    //draw clock
    turtle.penColor(.deepPurple)
    turtle.penSize(2)
    turtle.penUp()
    turtle.goto(180,-35)
    turtle.penDown()
    turtle.curve(withSides: 15, withSize: 20, drawSides: 15)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(45)
    turtle.penDown()
    turtle.right(90)
    turtle.forward(50)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(50)
    turtle.penDown()
    turtle.left(100)
    turtle.forward(30)
    
    //draw clock
    turtle.penColor(.green)
    turtle.penSize(2)
    turtle.penUp()
    turtle.goto(100,-160)
    turtle.penDown()
    turtle.curve(withSides: 15, withSize: 20, drawSides: 15)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(45)
    turtle.penDown()
    turtle.right(90)
    turtle.forward(50)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(50)
    turtle.penDown()
    turtle.left(100)
    turtle.forward(30)

    // Hide the turtle when done
    turtle.hideTortoise()
    
}
